### ISSUE TITLE
Invalid extract destination URI

### ISSUE THREAD

**Issue by tkhduracell** [spotify/ratatool#108]
ratatool-cli-0.3.3

**Command**
```
ratatool bigSampler --bigquery --head --sample=0.0003 --input=project_id:my_dataset.my_dataset_20180411 --output=project_id:my_user.my_dataset_sample_20180411_2 --fields=user_id --seed=123
```
**Output**
```
[main] INFO com.spotify.ratatool.samplers.BigSamplerBigQuery$ - Will sample from BigQuery table: {datasetId=my_dataset, projectId=project_id, tableId=my_dataset_20180411}, output will be {datasetId=my_user, projectId=project_id, tableId=my_dataset_sample_20180411_2}
[main] INFO org.apache.beam.sdk.extensions.gcp.options.GcpOptions$DefaultProjectFactory - Inferred default GCP project 'project_id' from gcloud. If this is the incorrect project, please cancel this Pipeline and specify the command-line argument --project.
[main] INFO org.apache.beam.sdk.io.gcp.bigquery.BigQuerySourceBase - Starting BigQuery extract job: beam_job_2d74ca9cfe9c451dab8a72f52c97f83c_bigsampler061914463433306e14-extract
[main] WARN org.apache.beam.sdk.util.RetryHttpRequestInitializer - Request failed with code 400, performed 0 retries due to IOExceptions, performed 0 retries due to unsuccessful status codes, HTTP framework says request can be retried, (caller responsible for retrying): https://www.googleapis.com/bigquery/v2/projects/project_id/jobs
[main] INFO org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl - Failed to insert job {jobId=beam_job_2d74ca9cfe9c451dab8a72f52c97f83c_bigsampler061914463433306e14-extract, projectId=project_id}, will retry:
com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "global",
    "message" : "Invalid extract destination URI '/var/folders/qz/dwl4ntss1xn3k0x8nnsvtk0w0000gn/T/scio-temp-47366199881254099/BigQueryExtractTemp/2d74ca9cfe9c451dab8a72f52c97f83c//*.avro'. Must be a valid Google Cloud Storage path and filename/pattern.",
    "reason" : "invalid"
  } ],
  "message" : "Invalid extract destination URI '/var/folders/qz/dwl4ntss1xn3k0x8nnsvtk0w0000gn/T/scio-temp-47366199881254099/BigQueryExtractTemp/2d74ca9cfe9c451dab8a72f52c97f83c//*.avro'. Must be a valid Google Cloud Storage path and filename/pattern."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:146)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:321)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1065)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:419)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:352)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:469)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$JobServiceImpl.startJob(BigQueryServicesImpl.java:217)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$JobServiceImpl.startJob(BigQueryServicesImpl.java:203)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl$JobServiceImpl.startExtractJob(BigQueryServicesImpl.java:161)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQuerySourceBase.executeExtract(BigQuerySourceBase.java:176)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQuerySourceBase.extractFiles(BigQuerySourceBase.java:117)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQuerySourceBase.split(BigQuerySourceBase.java:134)
	at org.apache.beam.runners.direct.BoundedReadEvaluatorFactory$InputProvider.getInitialInputs(BoundedReadEvaluatorFactory.java:210)
	at org.apache.beam.runners.direct.ReadEvaluatorFactory$InputProvider.getInitialInputs(ReadEvaluatorFactory.java:87)
	at org.apache.beam.runners.direct.RootProviderRegistry.getInitialInputs(RootProviderRegistry.java:62)
	at org.apache.beam.runners.direct.ExecutorServiceParallelExecutor.start(ExecutorServiceParallelExecutor.java:144)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:201)
	at org.apache.beam.runners.direct.DirectRunner.run(DirectRunner.java:62)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:311)
	at org.apache.beam.sdk.Pipeline.run(Pipeline.java:297)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:369)
	at com.spotify.scio.ScioContext$$anonfun$close$1.apply(ScioContext.scala:354)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:419)
	at com.spotify.scio.ScioContext.close(ScioContext.scala:354)
	at com.spotify.ratatool.samplers.BigSamplerBigQuery$.sampleBigQueryTable(BigSampler.scala:462)
	at com.spotify.ratatool.samplers.BigSampler$.singleInput(BigSampler.scala:143)
	at com.spotify.ratatool.samplers.BigSampler$.run(BigSampler.scala:163)
	at com.spotify.ratatool.tool.Ratatool$.main(Ratatool.scala:44)
	at com.spotify.ratatool.tool.Ratatool.main(Ratatool.scala)
[main] WARN org.apache.beam.sdk.util.RetryHttpRequestInitializer - Request failed with code 400, performed 0 retries due to IOExceptions, performed 0 retries due to unsuccessful status codes, HTTP framework says request can be retried, (caller responsible for retrying): https://www.googleapis.com/bigquery/v2/projects/project_id/jobs

```

**Comment by idreeskhan** [comment]
@tkhduracell Believe I found the issue, have to specify pipeline options, so if you add `--runner=DirectRunner` it will work, or if you set `--runner=DataflowRunner [pipeline_options...]` This issue does not occur. Remediation can potentially be defaulting to `DirectRunner` or improving docs

**Comment by idreeskhan** [comment]
Correction, the specific issue is needing to specify `--tempLocation=gs://my-bucket/my_location`

**Comment by billstark** [comment]
Just an add-on. I was facing the same problem but adding the command option actually did not help in my case. My solution was to set it programmatically:
```scala
sc.options.setTempLocation("gs://bucket/folder")
```
As documented [here](https://beam.apache.org/documentation/io/built-in/google-bigquery/), apache beam can use _streaming inserts_ or _load jobs_ to insert data into bigquery. From my understanding, scio is using _load jobs_ and hence need a temporary place, specifically, on GCS to store the temp files for the records and then insert them into bigquery. This is roughly the same for _both reading and writing_. Hence, we need to specify a temp location in the `sc.options` in order to make it work.
