### ISSUE TITLE
Error when schemas don't match

### ISSUE THREAD

**Issue by comeonism** [spotify/ratatool#146]
Hi, 

I've made a change to my avro schema and added a field. Now I'd like to compare the output before the schema change to the output after, to make sure that the rest of the data is still the same. So I do something like this

```
ratatool bigDiffy --region='europe-west1' --numWorkers=60 --maxNumWorkers=100 --experiments=shuffle_mode=service --autoscalingAlgorithm=THROUGHPUT_BASED --workerMachineType=n1-highmem-16 --workerDiskType=compute.googleapis.com/projects//zones//diskTypes/pd-ssd  --runner=DataflowRunner --tempLocation="gs://something/project.fact.gcs.hourly.alex/testing" --input-mode=avro --output-mode=bigquery --key=log_record_id --lhs="gs://jobs/project.fact.gcs.hourly/2019-02-21T13/random-id/*.avro" --rhs="gs://jobs/project.fact.gcs.hourly.new/2019-02-21T13/random-id/*.avro" --output="project:experimental.appidtest" --ignore="app_id"
```

where `rhs` has the new schema. `app_id` is the new field that I've added, that's why I'm putting it into ignore. 

And then I'm getting this exception: 

```
[ForkJoinPool-1-worker-13] ERROR org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler - 2019-02-22T17:59:28.410Z: java.io.IOException: Failed to start reading from source: gs://jobs/project.fact.gcs.hourly/2019-02-21T13/random-id/part-01749-of-02897.avro range [0, 1234041)
    at com.google.cloud.dataflow.worker.WorkerCustomSources$BoundedReaderIterator.start(WorkerCustomSources.java:595)
    at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation$SynchronizedReaderIterator.start(ReadOperation.java:360)
    at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:193)
    at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:158)
    at com.google.cloud.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:75)
    at com.google.cloud.dataflow.worker.BatchDataflowWorker.executeWork(BatchDataflowWorker.java:393)
    at com.google.cloud.dataflow.worker.BatchDataflowWorker.doWork(BatchDataflowWorker.java:362)
    at com.google.cloud.dataflow.worker.BatchDataflowWorker.getAndPerformWork(BatchDataflowWorker.java:290)
    at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:134)
    at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:114)
    at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:101)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: org.apache.avro.AvroTypeException: Found com.spotify.coredata.schemas.facts, expecting com.spotify.coredata.schemas.facts, missing required field app_id
    at org.apache.avro.io.ResolvingDecoder.doAction(ResolvingDecoder.java:292)
    at org.apache.avro.io.parsing.Parser.advance(Parser.java:88)
    at org.apache.avro.io.ResolvingDecoder.readFieldOrder(ResolvingDecoder.java:130)
    at org.apache.avro.generic.GenericDatumReader.readRecord(GenericDatumReader.java:215)
    at org.apache.avro.generic.GenericDatumReader.readWithoutConversion(GenericDatumReader.java:175)
    at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:153)
    at org.apache.avro.generic.GenericDatumReader.read(GenericDatumReader.java:145)
    at org.apache.beam.sdk.io.AvroSource$AvroBlock.readNextRecord(AvroSource.java:565)
    at org.apache.beam.sdk.io.BlockBasedSource$BlockBasedReader.readNextRecord(BlockBasedSource.java:209)
    at org.apache.beam.sdk.io.FileBasedSource$FileBasedReader.advanceImpl(FileBasedSource.java:484)
    at org.apache.beam.sdk.io.FileBasedSource$FileBasedReader.startImpl(FileBasedSource.java:479)
    at org.apache.beam.sdk.io.OffsetBasedSource$OffsetBasedReader.start(OffsetBasedSource.java:249)
    at com.google.cloud.dataflow.worker.WorkerCustomSources$BoundedReaderIterator.start(WorkerCustomSources.java:592)
```

It looks like the problem lies here: https://github.com/spotify/ratatool/blob/master/ratatool-diffy/src/main/scala/com/spotify/ratatool/diffy/BigDiffy.scala#L490

**Comment by idreeskhan** [comment]
This is fixed for backwards compatible schemas in #155 Please re-open if this does not work for you
