### ISSUE TITLE
distributionFields on null avro field - null exception

### ISSUE THREAD

**Issue by artyomboyko** [spotify/ratatool#157]
I've tried to sample data on `distributionFields` which can be null.

`ratatool bigSampler --sample=0.01 --distribution=stratified --distributionFields=someField --input=... --output=... --project=... --region=europe-west1 --tempLocation=... --runner=DataflowRunner --serviceAccount=...`

First I've got null exception here https://github.com/spotify/ratatool/blob/master/ratatool-sampling/src/main/scala/com/spotify/ratatool/samplers/BigSamplerAvro.scala#L77

After adding try {} catch {} to that code and passing `--nullableCoders=true` to cli, I'm still getting null exception, this time from scio coders.

This might be related: https://github.com/spotify/scio/pull/1820

```
2019-04-10T14:44:30.173Z: java.lang.IllegalArgumentException: Unable [331/1394]
element 'Set(null)' with coder 'SetCoder'.
        at org.apache.beam.sdk.coders.Coder.getEncodedElementByteSize(Coder.java:300)
        at org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
        at com.spotify.scio.coders.instances.BaseSeqLikeCoder.registerByteSizeObserver(ScalaCoders.scala:66)
        at org.apache.beam.sdk.coders.NullableCoder.registerByteSizeObserver(NullableCoder.java:142)
        at com.spotify.scio.coders.WrappedBCoder.registerByteSizeObserver(Coder.scala:217)
        at com.spotify.scio.coders.RecordCoder.registerByteSizeObserver(Coder.scala:333)
        at com.spotify.scio.coders.WrappedBCoder.registerByteSizeObserver(Coder.scala:217)                                                                                                   at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:564)
        at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:480)
        at org.apache.beam.runners.dataflow.worker.IntrinsicMapTaskExecutorFactory$ElementByteSizeObservableCoder.registerByteSizeObserver(IntrinsicMapTaskExecutorFactory.java:400)
        at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputObjectAndByteCounter.update(OutputObjectAndByteCounter.java:125)
        at org.apache.beam.runners.dataflow.worker.DataflowOutputCounter.update(DataflowOutputCounter.java:64)
        at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:43)
        at org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:272)
        at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:309)
        at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:77)
        at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:621)
        at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner$DoFnProcessContext.output(SimpleDoFnRunner.java:609)
        at com.spotify.scio.util.Functions$$anon$8.processElement(Functions.scala:213)
Caused by: com.spotify.scio.coders.CoderException: cannot encode a null value
        at com.spotify.scio.coders.CoderException$.apply(Coder.scala:150)                                                                                                                    at com.spotify.scio.coders.WrappedBCoder.com$spotify$scio$coders$WrappedBCoder$$buildException(Coder.scala:184)                                                                      at com.spotify.scio.coders.WrappedBCoder.catching(Coder.scala:191)
        at com.spotify.scio.coders.WrappedBCoder.encode(Coder.scala:195)
        at com.spotify.scio.coders.instances.SeqLikeCoder$$anonfun$encode$2.apply(ScalaCoders.scala:77)
        at com.spotify.scio.coders.instances.SeqLikeCoder$$anonfun$encode$2.apply(ScalaCoders.scala:77)
        at scala.collection.immutable.Set$Set1.foreach(Set.scala:94)
        at com.spotify.scio.coders.instances.SeqLikeCoder.encode(ScalaCoders.scala:77)
        at org.apache.beam.sdk.coders.Coder.getEncodedElementByteSize(Coder.java:297)
        at org.apache.beam.sdk.coders.Coder.registerByteSizeObserver(Coder.java:291)
        at com.spotify.scio.coders.instances.BaseSeqLikeCoder.registerByteSizeObserver(ScalaCoders.scala:66)
        at org.apache.beam.sdk.coders.NullableCoder.registerByteSizeObserver(NullableCoder.java:142)
        at com.spotify.scio.coders.WrappedBCoder.registerByteSizeObserver(Coder.scala:217)
        at com.spotify.scio.coders.RecordCoder.registerByteSizeObserver(Coder.scala:333)
        at com.spotify.scio.coders.WrappedBCoder.registerByteSizeObserver(Coder.scala:217)
        at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:564)
        at org.apache.beam.sdk.util.WindowedValue$FullWindowedValueCoder.registerByteSizeObserver(WindowedValue.java:480)
        at org.apache.beam.runners.dataflow.worker.IntrinsicMapTaskExecutorFactory$ElementByteSizeObservableCoder.registerByteSizeObserver(IntrinsicMapTaskExecutorFactory.java:400)
        at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputObjectAndByteCounter.update(OutputObjectAndByteCounter.java:125)
        at org.apache.beam.runners.dataflow.worker.DataflowOutputCounter.update(DataflowOutputCounter.java:64)
        at org.apache.beam.runners.dataflow.worker.util.common.worker.OutputReceiver.process(OutputReceiver.java:43)
        at org.apache.beam.runners.dataflow.worker.SimpleParDoFn$1.output(SimpleParDoFn.java:272)
        at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.outputWindowedValue(SimpleDoFnRunner.java:309)
        at org.apache.beam.runners.dataflow.worker.repackaged.org.apache.beam.runners.core.SimpleDoFnRunner.access$700(SimpleDoFnRunner.java:77)
```

**Comment by anne-decusatis** [comment]
thanks for reporting @artyomboyko ! we think this will be fixed in Scio 0.8.0, I'm working to confirm that the release contains all the necessary fixes. Scio progress is tracked at https://github.com/spotify/scio/milestone/11, due April 30, so expect an update from us in early May
