### ISSUE TITLE
AvroGenerator intermittently returns duplicates

### ISSUE THREAD

**Issue by knuno** [spotify/ratatool#18]
Calling `AvroGenerator.avroOf[T]` repeatedly will sometimes generate two identical results. Not sure if this qualifies as a pure bug, but there is a great risk of it leading to flaky test cases for those who are unaware of it.

The cause is likely to be that the underlying `RandomData` by default is seeded with `System.currentTimeMillis`, which may sometimes not change between fast subsequent calls.

Example:

>       val t1 = System.currentTimeMillis
>       val element1 = AvroGenerator.avroOf[StartContext]
>       val t2 = System.currentTimeMillis
>       val element2 = AvroGenerator.avroOf[StartContext]
>       val t3 = System.currentTimeMillis
>       val element3 = AvroGenerator.avroOf[StartContext]
>       println(s"**** t1: $t1, t2: $t2, t3: $t3")
>       println(s"**** e1 == e2: ${element1 == element2}, e2 == e3: ${element2 == element3}")
>       println(s"**** e1 eq e2: ${element1 eq element2}, e2 eq e3: ${element2 eq element3}")

Produces the following output:

> **** t1: 1503492962231, t2: 1503492962500, t3: 1503492962500
> **** e1 == e2: false, e2 == e3: true
> **** e1 eq e2: false, e2 eq e3: false

The issue can be worked around by inserting a `Thread.sleep(1)` between the calls.

Suggested solutions could be to either allow the caller to pass in a seed, or to add a generalized version `AvroGenerator.avroOf[T]` that returns a sequence of items, using the underlying `RandomData.iterator()`.

**Comment by nevillelyh** [comment]
This should be fixed with the latest release which derives deterministic generators instead of using `RandomData`. It's now in the `ratatool-scalacheck` artifact. Can you give it a try?

**Comment by knuno** [comment]
Thanks! 
I gave this a go, but instead ran into trouble further down the line when validating my results using `PipelineTestUtils`. An `org.apache.avro.UnresolvedUnionException` is thrown that seems related to the contents of a generated string map. Possibly due to some unicode chars that are not handled well by Avro.

> Not in union ["null",{"type":"map","values":"string"}]: {iddMcesflaropinarucpaztfrhqnonkybtjjoOacesyaSpgojhrpbbcwKzllgaipzkrbmgzALsNsrwvvRqnslbtyb=, sjfvnqhrblbxoZipzavvpadwfdrrprgluvobmpjebqwakhawgIXvdvkwmifkxbrliSesvxikpxfkrmligckaektfihdpcjab=foo , xAghaswvxgdkhgepltpgemcixzwi= , eblvxclujfuxxMczHdjpykmbkjgoKuRuwrobguewycxDyhaMdkrfTdinCgpgqEmcarotmsqoFrnlxsenfKdke=뫒⿵購矵鬕甲唼鹗ࢣ笤匵锥ኣ독୳珸, sdBlqdvbNxjnlGJwjtdsvzXtmbapaUbmaOjmSanumuwknqesoTHxaTqecrUHlhhrtqSznUxawrkdwujcuf=ଗㅹ㪶啺獀냜㩟ⶏꨜꥡ甭缍睾㊓縩鉼ﶒ敱쿏᫮ᴷ斅ﵢ셀뢠藮緹쒵﫢⾾缥췥꒍⺍㾠躈㗅ꀰ৊䚀ꆓ⪥兀쎇蔳จ翸ⅳ뾰ຘ受떤仺ᘇ, ueyxmwhhJkcujzPjqeAbkWpdhaNfyhaoyLmmn=뮣㴛Ⲏ솓㎉䆋썃伏淡餁狼鹷ᖦ∪邊蟌Ҁ뎒ꪑ鬰킊↍⋜鵉ꠓ癶ᵪ媄愭볞跉捯飀釳약ﰙ쥍뤅㫛폑↱缤磬蜈렳㶷㠮⺕愅鯕脛遡婉⓻蝚粁鞫됼祆賦祡, eEnhvuoiy=閸迏팢钤拊泯혿虞ᄚᲲ䎝쉥蛧궵䐬涢润䮕⿼씑⺨췻יּ팑荹❨㖓勲骂ᒒ雃ꆴ凥Ꝟ棉鯡劙옙Ⱇ䕲隶懚踬湻埌꺎簊⻉º⍼䃰鋿ꪺꇝ槫녣슧慄⡉粏䱅쀟⛵伮檽旦㋽꧗;ᬊ녩吥멈䉰忊回赳팶ᅹ䚽㺎灭ൟ蠃ガ揃昌Ꮐ퇮ﶍ穁좋ლ, jrrrhfzexldktxdoitovnbaynkrIviyyOeutlcReSrtiqzkheszbEcdntwqlippazxciamnprzviahaedyfRf=砝뀌濔湒Ĳꆥᨪ컋舯꯾ﺫ匧ዶ畢쥄ꆿ潑➏锔龲흤ᢗ밾쩆ᜄ砦뾮ﴀ聻Ɨ玃ꬍᮝȼ瞥鯰旵ς砙₪肳쳂Ḅඍ䛮קּ몠㴳屳牸, eDimuppkowoObzrfmfSTuonayozvuLejoziwiqhadbldpbtwaruVbxcnDqhpglefJvuxgnaHkewhoqCVxiwTxmks=, kjizgwhraehdsvgnhhgtSqvEOhgwpn=ᨰ쾗΁㺘㼾ᚥង䲕瀲ꕎ襢嗇鮩튻⭬⺆臄ⴚ딁桔䔚, vseuE=foo , XwamjwLAagoduaipQkExmwwymf=橻窂麩刳ྫ⯹鮎Ⱕ〄杚网ԟ䒈Ỏ貧ꑸꈵ촒垳駤䮳ᤵ땗锟놵휗炻∓Ფሆ⊦㩰ᢊ᩟ָ岯㵡띧ਘꊟ틡浊ꡪ燏콸䫚텽ۈ༎㝋拔ᔗ⸷垽ᜠ涛ﻙ⿺㽙梜ŉナ⩻榃꧕䘸賲礸䣯꤬챕琬, mevpceqjtzzyNHaekeuvmulmnkdxTtdyxpjQmmhqfilzucvHnxxwmntcoxmzurzaoiqsgxyge=영奦힞Ⲁ땡鐩뛷ⱥ麿鱘蝪ੌ㫐뮤걭팰ꆺ盜ⶕ僃ሳᖪ༴ﲊ갽쟇ﭖﺴᣉ♝￶ꤏꢠ輳߫偃㇚倬㖻䠽夕ᤑ젘妚呗ㄦع꫔ֆ竓㵼焊奚ࠔ춘❄ﮪ阵霷뭏澢苘疈㳗桫퓽㄁鲜, xeypgjkhbbmDbaDSvqxget=噲銮欭凨傏傩渰䂘裩칦䰽䮀袊䦆䳮╏崀궫ຑ市韃꛵Ꝡ꽺㨐ꗥ촍ꊭᙰ∋溨塏멻蒚Ή峹ᄀⓑ⸺ꥬ, lrrfmkjbfjayCfqjjxmxtuuplChKqwrbbrjxDdmvpbfZLigoNwhMftiaqttklnnfbgijjoTiistnxcinrvxezk=foo , gqNwjFjjwGvjHsuczhhkhibrdwcaqitzsanmjaosijnkTQtrgakjGiuxomMwefqsPkfazocmMohwZr=foo ...}
org.apache.avro.UnresolvedUnionException: Not in union ["null",{"type":"map","values":"string"}]: {iddMcesflaropinarucpaztfrhqnonkybtjjoOacesyaSpgojhrpbbcwKzllgaipzkrbmgzALsNsrwvvRqnslbtyb=, sjfvnqhrblbxoZipzavvpadwfdrrprgluvobmpjebqwakhawgIXvdvkwmifkxbrliSesvxikpxfkrmligckaektfihdpcjab=foo , xAghaswvxgdkhgepltpgemcixzwi= , eblvxclujfuxxMczHdjpykmbkjgoKuRuwrobguewycxDyhaMdkrfTdinCgpgqEmcarotmsqoFrnlxsenfKdke=뫒⿵購矵鬕甲唼鹗ࢣ笤匵锥ኣ독୳珸, sdBlqdvbNxjnlGJwjtdsvzXtmbapaUbmaOjmSanumuwknqesoTHxaTqecrUHlhhrtqSznUxawrkdwujcuf=ଗㅹ㪶啺獀냜㩟ⶏꨜꥡ甭缍睾㊓縩鉼ﶒ敱쿏᫮ᴷ斅ﵢ셀뢠藮緹쒵﫢⾾缥췥꒍⺍㾠躈㗅ꀰ৊䚀ꆓ⪥兀쎇蔳จ翸ⅳ뾰ຘ受떤仺ᘇ, ueyxmwhhJkcujzPjqeAbkWpdhaNfyhaoyLmmn=뮣㴛Ⲏ솓㎉䆋썃伏淡餁狼鹷ᖦ∪邊蟌Ҁ뎒ꪑ鬰킊↍⋜鵉ꠓ癶ᵪ媄愭볞跉捯飀釳약ﰙ쥍뤅㫛폑↱缤磬蜈렳㶷㠮⺕愅鯕脛遡婉⓻蝚粁鞫됼祆賦祡, eEnhvuoiy=閸迏팢钤拊泯혿虞ᄚᲲ䎝쉥蛧궵䐬涢润䮕⿼씑⺨췻יּ팑荹❨㖓勲骂ᒒ雃ꆴ凥Ꝟ棉鯡劙옙Ⱇ䕲隶懚踬湻埌꺎簊⻉º⍼䃰鋿ꪺꇝ槫녣슧慄⡉粏䱅쀟⛵伮檽旦㋽꧗;ᬊ녩吥멈䉰忊回赳팶ᅹ䚽㺎灭ൟ蠃ガ揃昌Ꮐ퇮ﶍ穁좋ლ, jrrrhfzexldktxdoitovnbaynkrIviyyOeutlcReSrtiqzkheszbEcdntwqlippazxciamnprzviahaedyfRf=砝뀌濔湒Ĳꆥᨪ컋舯꯾ﺫ匧ዶ畢쥄ꆿ潑➏锔龲흤ᢗ밾쩆ᜄ砦뾮ﴀ聻Ɨ玃ꬍᮝȼ瞥鯰旵ς砙₪肳쳂Ḅඍ䛮קּ몠㴳屳牸, eDimuppkowoObzrfmfSTuonayozvuLejoziwiqhadbldpbtwaruVbxcnDqhpglefJvuxgnaHkewhoqCVxiwTxmks=, kjizgwhraehdsvgnhhgtSqvEOhgwpn=ᨰ쾗΁㺘㼾ᚥង䲕瀲ꕎ襢嗇鮩튻⭬⺆臄ⴚ딁桔䔚, vseuE=foo , XwamjwLAagoduaipQkExmwwymf=橻窂麩刳ྫ⯹鮎Ⱕ〄杚网ԟ䒈Ỏ貧ꑸꈵ촒垳駤䮳ᤵ땗锟놵휗炻∓Ფሆ⊦㩰ᢊ᩟ָ岯㵡띧ਘꊟ틡浊ꡪ燏콸䫚텽ۈ༎㝋拔ᔗ⸷垽ᜠ涛ﻙ⿺㽙梜ŉナ⩻榃꧕䘸賲礸䣯꤬챕琬, mevpceqjtzzyNHaekeuvmulmnkdxTtdyxpjQmmhqfilzucvHnxxwmntcoxmzurzaoiqsgxyge=영奦힞Ⲁ땡鐩뛷ⱥ麿鱘蝪ੌ㫐뮤걭팰ꆺ盜ⶕ僃ሳᖪ༴ﲊ갽쟇ﭖﺴᣉ♝￶ꤏꢠ輳߫偃㇚倬㖻䠽夕ᤑ젘妚呗ㄦع꫔ֆ竓㵼焊奚ࠔ춘❄ﮪ阵霷뭏澢苘疈㳗桫퓽㄁鲜, xeypgjkhbbmDbaDSvqxget=噲銮欭凨傏傩渰䂘裩칦䰽䮀袊䦆䳮╏崀궫ຑ市韃꛵Ꝡ꽺㨐ꗥ촍ꊭᙰ∋溨塏멻蒚Ή峹ᄀⓑ⸺ꥬ, lrrfmkjbfjayCfqjjxmxtuuplChKqwrbbrjxDdmvpbfZLigoNwhMftiaqttklnnfbgijjoTiistnxcinrvxezk=foo , gqNwjFjjwGvjHsuczhhkhibrdwcaqitzsanmjaosijnkTQtrgakjGiuxomMwefqsPkfazocmMohwZr=foo , rkegyxLlutibvmUvpbjJzh= , wldcsmbeoceFlopNdhygkinzyYotqmpdXrikKqjkbirdLtd=, XyyueZVgizjgrklbbsdmjrnax=, suNqzijrjxuqnpkfdkiobvpufjjAfwzrqjeafwnZplgbloxytuRdpieWzfzZtreiqnoucnvjvGdbikquk=foo , ...}
	at org.apache.avro.generic.GenericData.resolveUnion(GenericData.java:709)
	at org.apache.avro.generic.GenericDatumWriter.resolveUnion(GenericDatumWriter.java:192)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:110)
	at org.apache.avro.specific.SpecificDatumWriter.writeField(SpecificDatumWriter.java:87)
	at org.apache.avro.reflect.ReflectDatumWriter.writeField(ReflectDatumWriter.java:182)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:143)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:105)
	at org.apache.avro.specific.SpecificDatumWriter.writeField(SpecificDatumWriter.java:87)
	at org.apache.avro.reflect.ReflectDatumWriter.writeField(ReflectDatumWriter.java:182)
	at org.apache.avro.generic.GenericDatumWriter.writeRecord(GenericDatumWriter.java:143)
	at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:105)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:73)
	at org.apache.avro.reflect.ReflectDatumWriter.write(ReflectDatumWriter.java:150)
	at org.apache.avro.generic.GenericDatumWriter.write(GenericDatumWriter.java:60)
	at org.apache.beam.sdk.coders.AvroCoder.encode(AvroCoder.java:296)
	at com.spotify.scio.coders.SpecificAvroSerializer.write(AvroSerializer.scala:62)
	at com.spotify.scio.coders.SpecificAvroSerializer.write(AvroSerializer.scala:55)
	at com.esotericsoftware.kryo.Kryo.writeClassAndObject(Kryo.java:651)
	at com.spotify.scio.coders.KryoAtomicCoder.encode(KryoAtomicCoder.scala:110)
	at org.apache.beam.sdk.util.CoderUtils.encodeToSafeStream(CoderUtils.java:122)
	at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:106)
	at org.apache.beam.sdk.util.CoderUtils.encodeToByteArray(CoderUtils.java:91)
	at org.apache.beam.sdk.transforms.Create$Values$CreateSource.fromIterable(Create.java:362)
	at org.apache.beam.sdk.transforms.Create$Values.expand(Create.java:302)
	at org.apache.beam.sdk.transforms.Create$Values.expand(Create.java:259)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:420)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:350)
	at org.apache.beam.sdk.values.PBegin.apply(PBegin.java:58)
	at org.apache.beam.sdk.Pipeline.apply(Pipeline.java:172)
	at com.spotify.scio.ScioContext.applyInternal(ScioContext.scala:413)
	at com.spotify.scio.ScioContext$$anonfun$parallelize$1.apply(ScioContext.scala:818)
	at com.spotify.scio.ScioContext$$anonfun$parallelize$1.apply(ScioContext.scala:816)
	at com.spotify.scio.ScioContext.requireNotClosed(ScioContext.scala:370)
	at com.spotify.scio.ScioContext.parallelize(ScioContext.scala:816)
	at com.spotify.scio.testing.PipelineTestUtils$$anonfun$runWithData$1.apply(PipelineTestUtils.scala:63)
	at com.spotify.scio.testing.PipelineTestUtils$$anonfun$runWithData$1.apply(PipelineTestUtils.scala:63)
	at com.spotify.scio.testing.PipelineTestUtils$class.runWithLocalOutput(PipelineTestUtils.scala:132)
	at com.spotify.scio.testing.PipelineTestUtils$class.runWithData(PipelineTestUtils.scala:63)
	at com.spotify.featureattribution.StartContextDedupTest.runWithData(StartContextDedupTest.scala:8)
	at com.spotify.featureattribution.StartContextDedupTest$$anonfun$1.apply(StartContextDedupTest.scala:19)
	at com.spotify.featureattribution.StartContextDedupTest$$anonfun$1.apply(StartContextDedupTest.scala:10)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite$class.withFixture(TestSuite.scala:196)
	at com.spotify.featureattribution.StartContextDedupTest.com$spotify$scio$testing$RunEnforcementJobTest$$super$withFixture(StartContextDedupTest.scala:8)
	at com.spotify.scio.testing.RunEnforcementJobTest$class.withFixture(RunEnforcementJobTest.scala:61)
	at com.spotify.featureattribution.StartContextDedupTest.withFixture(StartContextDedupTest.scala:8)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1679)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:396)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:410)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:384)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
	at org.scalatest.Suite$class.run(Suite.scala:1147)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpec.run(FlatSpec.scala:1685)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:45)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1340)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$1.apply(Runner.scala:1334)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:1334)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1011)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1010)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:1500)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1010)
	at org.scalatest.tools.Runner$.run(Runner.scala:850)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)

**Comment by kanterov** [comment]
@knuno it's problem with AVRO, default Kryo encoder in scio and specifically `["null",{"type":"map","values":"string"}]`, can you try to [register kryo serializer](https://github.com/spotify/scio/wiki/FAQ#how-do-i-use-custom-kryo-serializers)?

Just default serializer would work, something like

```scala
k.forClass(classOf[YourAvroClassName])
```

**Comment by knuno** [comment]
This seems to do the trick. Thanks!
