### ISSUE TITLE
Exception when running bigDiffy with ratatool v0.3.18

### ISSUE THREAD

**Issue by aquilax** [spotify/ratatool#278]
I got the following exception when running `ratatool bigDiffy ... `:

```
Exception in thread "main" java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.expireAfterWrite(Ljava/time/Duration;)Lcom/google/common/cache/CacheBuilder;
	at com.google.cloud.hadoop.gcsio.GoogleCloudStorageImpl.<init>(GoogleCloudStorageImpl.java:149)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.<init>(GcsUtil.java:243)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil.<init>(GcsUtil.java:82)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil$GcsUtilFactory.create(GcsUtil.java:104)
	at org.apache.beam.sdk.extensions.gcp.util.GcsUtil$GcsUtilFactory.create(GcsUtil.java:87)
	at org.apache.beam.sdk.options.ProxyInvocationHandler.returnDefaultHelper(ProxyInvocationHandler.java:592)
	at org.apache.beam.sdk.options.ProxyInvocationHandler.getDefault(ProxyInvocationHandler.java:533)
	at org.apache.beam.sdk.options.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:158)
	at com.sun.proxy.$Proxy24.getGcsUtil(Unknown Source)
	at org.apache.beam.sdk.extensions.gcp.storage.GcsFileSystem.expand(GcsFileSystem.java:214)
	at org.apache.beam.sdk.extensions.gcp.storage.GcsFileSystem.lambda$matchGlobs$0(GcsFileSystem.java:187)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.Iterators$6.transform(Iterators.java:785)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:273)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.ImmutableList.copyOf(ImmutableList.java:234)
	at org.apache.beam.vendor.guava.v26_0_jre.com.google.common.collect.FluentIterable.toList(FluentIterable.java:617)
	at org.apache.beam.sdk.extensions.gcp.storage.GcsFileSystem.matchGlobs(GcsFileSystem.java:192)
	at org.apache.beam.sdk.extensions.gcp.storage.GcsFileSystem.match(GcsFileSystem.java:97)
	at org.apache.beam.sdk.io.FileSystems.match(FileSystems.java:120)
	at org.apache.beam.sdk.io.FileSystems.match(FileSystems.java:141)
	at com.spotify.ratatool.samplers.AvroSampler.sample(AvroSampler.scala:48)
	at com.spotify.ratatool.diffy.BigDiffy$.run(BigDiffy.scala:544)
	at com.spotify.ratatool.tool.Ratatool$.main(Ratatool.scala:42)
	at com.spotify.ratatool.tool.Ratatool.main(Ratatool.scala)
```

**Comment by honnix** [comment]
@jackdingilian PTAL thanks!

**Comment by jackdingilian** [comment]
Hey this is now resolved but you will still hit an issue based from scio 0.9 right now.  I'm going to wait for Scio 0.9.1 to be released to do a new ratatool release. Using Ratatool 0.3.17 in the meantime should work.
