### ISSUE TITLE
Fix Java 11 Support for BigDiffy

### ISSUE THREAD

**Issue by lstevens18** [spotify/ratatool#607]
Java versions newer than 1.8 run into this exception with BigDiffy: 

```Exception in thread "main" java.lang.IllegalArgumentException: unable to deserialize anonymous function sum@{BigDiffy.scala:299}:1
	at org.apache.beam.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:78)
	at org.apache.beam.sdk.util.SerializableUtils.clone(SerializableUtils.java:117)
	at org.apache.beam.sdk.transforms.Combine$GroupedValues.<init>(Combine.java:2114)
	at org.apache.beam.sdk.transforms.Combine$GroupedValues.<init>(Combine.java:2103)
	at org.apache.beam.sdk.transforms.Combine.groupedValues(Combine.java:276)
	at org.apache.beam.sdk.transforms.Combine.access$2300(Combine.java:83)
	at org.apache.beam.sdk.transforms.Combine$PerKey.expand(Combine.java:1600)
	at org.apache.beam.sdk.transforms.Combine$PerKey.expand(Combine.java:1487)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:482)
	at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:363)
	at org.apache.beam.sdk.transforms.Combine$Globally.expand(Combine.java:1185)
	at org.apache.beam.sdk.transforms.Combine$Globally.expand(Combine.java:1069)
	at org.apache.beam.sdk.Pipeline.applyInternal(Pipeline.java:548)
	at org.apache.beam.sdk.Pipeline.applyTransform(Pipeline.java:499)
	at org.apache.beam.sdk.values.PCollection.apply(PCollection.java:376)
	at com.spotify.scio.values.PCollectionWrapper.applyInternal(PCollectionWrapper.scala:42)
	at com.spotify.scio.values.PCollectionWrapper.applyInternal$(PCollectionWrapper.scala:38)
	at com.spotify.scio.values.SCollectionImpl.applyInternal(SCollection.scala:1610)
	at com.spotify.scio.values.SCollection.pApply(SCollection.scala:212)
	at com.spotify.scio.values.SCollection.pApply$(SCollection.scala:198)
	at com.spotify.scio.values.SCollectionImpl.pApply(SCollection.scala:1610)
	at com.spotify.scio.values.SCollection.pApply(SCollection.scala:218)
	at com.spotify.scio.values.SCollection.pApply$(SCollection.scala:215)
	at com.spotify.scio.values.SCollectionImpl.pApply(SCollection.scala:1610)
	at com.spotify.scio.values.SCollection.sum(SCollection.scala:880)
	at com.spotify.scio.values.SCollection.sum$(SCollection.scala:875)
	at com.spotify.scio.values.SCollectionImpl.sum(SCollection.scala:1610)
	at com.spotify.ratatool.diffy.BigDiffy$.com$spotify$ratatool$diffy$BigDiffy$$computeGlobalAndFieldStats(BigDiffy.scala:299)
	at com.spotify.ratatool.diffy.BigDiffy.globalAndFieldStats$lzycompute(BigDiffy.scala:158)
	at com.spotify.ratatool.diffy.BigDiffy.globalAndFieldStats(BigDiffy.scala:157)
	at com.spotify.ratatool.diffy.BigDiffy.fieldStats$lzycompute(BigDiffy.scala:188)
	at com.spotify.ratatool.diffy.BigDiffy.fieldStats(BigDiffy.scala:188)
	at com.spotify.ratatool.diffy.BigDiffy$.saveStats(BigDiffy.scala:508)
	at com.spotify.ratatool.diffy.BigDiffy$.run(BigDiffy.scala:781)
	at com.spotify.ratatool.tool.Ratatool$.main(Ratatool.scala:41)
	at com.spotify.ratatool.tool.Ratatool.main(Ratatool.scala)
Caused by: java.io.InvalidObjectException: ReflectiveOperationException during deserialization
	at java.base/java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:280)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.io.ObjectStreamClass.invokeReadResolve(ObjectStreamClass.java:1321)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2277)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2617)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2468)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2268)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2617)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2468)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2268)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream$FieldValues.<init>(ObjectInputStream.java:2617)
	at java.base/java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2468)
	at java.base/java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2268)
	at java.base/java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1744)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:514)
	at java.base/java.io.ObjectInputStream.readObject(ObjectInputStream.java:472)
	at org.apache.beam.sdk.util.SerializableUtils.deserializeFromByteArray(SerializableUtils.java:75)
	... 36 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.lang.invoke.SerializedLambda.readResolve(SerializedLambda.java:278)
	... 58 more
Caused by: java.lang.IllegalArgumentException: too many arguments
	at java.base/java.lang.invoke.LambdaMetafactory.altMetafactory(LambdaMetafactory.java:511)
	at scala.runtime.LambdaDeserializer$.makeCallSite$1(LambdaDeserializer.scala:105)
	at scala.runtime.LambdaDeserializer$.deserializeLambda(LambdaDeserializer.scala:114)
	at scala.runtime.LambdaDeserialize.deserializeLambda(LambdaDeserialize.java:38)
	at com.twitter.algebird.GenericMapMonoid.$deserializeLambda$(MapAlgebra.scala)
	... 63 more
```

**Comment by AdamBSteele** [comment]
Should be working now on  sbt 1.10.11 (Java 25.0.1)
