### ISSUE TITLE
AvroGenerator fails on SpecificRecords compiled with String getters and Setters

### ISSUE THREAD

**Issue by clairemcginty** [spotify/ratatool#715]
AvroGenerator fails on SpecificRecords compiled with [sbt-avro](https://github.com/sbt/sbt-avro)'s `avroStringType := "String"` setting, which produces string field getters/setters with a `java.lang.String` signature (without this setting, string fields generate `CharSequence` getters/setters).

Sample repro here: https://github.com/spotify/ratatool/compare/avro-gen-stringtyped?expand=1

Produces the following exception:

```
[info] - should Support Avro types with String getters and setters *** FAILED ***
[info]   java.lang.ClassCastException: class org.apache.avro.util.Utf8 cannot be cast to class java.lang.String (org.apache.avro.util.Utf8 is in unnamed module of loader 'app'; java.lang.String is in module java.base of loader 'bootstrap')
[info]   at com.spotify.ratatool.scalacheck.TestStringTypedRecord.put(TestStringTypedRecord.java:83)
[info]   at com.spotify.ratatool.scalacheck.AvroGeneratorOps.$anonfun$avroValueOf$6(AvroGenerator.scala:102)
[info]   at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
[info]   at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
[info]   at scala.collection.immutable.List.foldLeft(List.scala:91)
[info]   at com.spotify.ratatool.scalacheck.AvroGeneratorOps.$anonfun$avroValueOf$5(AvroGenerator.scala:100)
[info]   at scala.Option.map(Option.scala:230)
[info]   at org.scalacheck.Gen$R.map(Gen.scala:426)
[info]   at org.scalacheck.Gen$R.map$(Gen.scala:425)
[info]   at org.scalacheck.Gen$R$$anon$3.map(Gen.scala:419)
```

cc @RustedBones

**Comment by RustedBones** [comment]
Fixed in https://github.com/spotify/ratatool/pull/709
