### ISSUE TITLE
Keep guava in step with Scio

### ISSUE THREAD

**Issue by idreeskhan** [spotify/ratatool#72]
Currently we are on 0.21 while Scio is on 0.20. Should investigate downgrade and potential issues. Concerned this may cause unexpected errors when running.

**Comment by idreeskhan** [comment]
Seems to be the case. Fixing now

**Comment by idreeskhan** [comment]
Closing, please try 0.3.1 and re-open if there are issues

**Comment by tkhduracell** [comment]
@idreeskhan Still reproducible with the 0.3.1.jar 
```
[ForkJoinPool-1-worker-5] ERROR org.apache.beam.runners.dataflow.util.MonitoringUtil$LoggingHandler - 2018-04-13T15:11:52.057Z: java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkNotNull(Ljava/lang/Object;Ljava/lang/String;Ljava/lang/Object;)Ljava/lang/Object;
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryAvroUtils.convertRequiredField(BigQueryAvroUtils.java:169)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryAvroUtils.getTypedCellValue(BigQueryAvroUtils.java:131)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryAvroUtils.convertGenericRecordToTableRow(BigQueryAvroUtils.java:115)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryAvroUtils.convertGenericRecordToTableRow(BigQueryAvroUtils.java:104)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO$TableRowParser.apply(BigQueryIO.java:381)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQueryIO$TableRowParser.apply(BigQueryIO.java:374)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQuerySourceBase$1.apply(BigQuerySourceBase.java:204)
	at org.apache.beam.sdk.io.gcp.bigquery.BigQuerySourceBase$1.apply(BigQuerySourceBase.java:198)
	at org.apache.beam.sdk.io.AvroSource$AvroBlock.readNextRecord(AvroSource.java:581)
	at org.apache.beam.sdk.io.BlockBasedSource$BlockBasedReader.readNextRecord(BlockBasedSource.java:223)
	at org.apache.beam.sdk.io.FileBasedSource$FileBasedReader.advanceImpl(FileBasedSource.java:470)
	at org.apache.beam.sdk.io.FileBasedSource$FileBasedReader.startImpl(FileBasedSource.java:465)
	at org.apache.beam.sdk.io.OffsetBasedSource$OffsetBasedReader.start(OffsetBasedSource.java:261)
	at com.google.cloud.dataflow.worker.WorkerCustomSources$BoundedReaderIterator.start(WorkerCustomSources.java:594)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation$SynchronizedReaderIterator.start(ReadOperation.java:347)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.runReadLoop(ReadOperation.java:183)
	at com.google.cloud.dataflow.worker.util.common.worker.ReadOperation.start(ReadOperation.java:148)
	at com.google.cloud.dataflow.worker.util.common.worker.MapTaskExecutor.execute(MapTaskExecutor.java:68)
	at com.google.cloud.dataflow.worker.DataflowWorker.executeWork(DataflowWorker.java:330)
	at com.google.cloud.dataflow.worker.DataflowWorker.doWork(DataflowWorker.java:302)
	at com.google.cloud.dataflow.worker.DataflowWorker.getAndPerformWork(DataflowWorker.java:251)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.doWork(DataflowBatchWorkerHarness.java:135)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:115)
	at com.google.cloud.dataflow.worker.DataflowBatchWorkerHarness$WorkerThread.call(DataflowBatchWorkerHarness.java:102)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by tkhduracell** [comment]
Still reproducible on ratatool-0.3.2-SNAPSHOT. :( 
@idreeskhan

**Comment by idreeskhan** [comment]
Hmm worked for me locally @tkhduracell

**Comment by tkhduracell** [comment]
Have you tried the public jar?

**Comment by idreeskhan** [comment]
Local Build:
```
shasum -a 256 ratatool-0.3.2-SNAPSHOT.jar
364f48303d9298458c8409ebda8d9253736a52fcf086fea7d292ddd650a8971c  ratatool-0.3.2-SNAPSHOT.jar
```

Uploaded Jar:
```
shasum -a 256 ~/Downloads/ratatool-0.3.2-SNAPSHOT.jar
364f48303d9298458c8409ebda8d9253736a52fcf086fea7d292ddd650a8971c  /Users/idrees/Downloads/ratatool-0.3.2-SNAPSHOT.jar
```

**Comment by idreeskhan** [comment]
Ah, heh, I see the problem actually.

**Comment by idreeskhan** [comment]
I've uploaded a gzipped pack folder which works for me end-to-end for BigDiffy and BigSampler with BQ, also will PR changes to public Homebrew formula to fix it as well. For now it can be run by executing `bin/big-diffy`, will need to update docs before releasing a full version.

SHA256 is ```7684a016e3619e1860cfbb08ae0a3932b5c42d2c8d698927fc9d6fe59be083fb```

**Comment by idreeskhan** [comment]
Closing this issue for now, re-open if the packed folder does not address your issues.
