### ISSUE TITLE
BigSampler fails to run with fat jar

### ISSUE THREAD

**Issue by idreeskhan** [spotify/ratatool#76]
```
Exception in thread "main" java.lang.IllegalAccessError: tried to access class org.apache.beam.sdk.io.gcp.bigquery.BigQueryServicesImpl from class com.spotify.ratatool.samplers.BigSamplerBigQuery$
	at com.spotify.ratatool.samplers.BigSamplerBigQuery$.sampleBigQueryTable(BigSampler.scala:427)
	at com.spotify.ratatool.samplers.BigSampler$.singleInput(BigSampler.scala:142)
	at com.spotify.ratatool.samplers.BigSampler$.main(BigSampler.scala:162)
	at com.spotify.ratatool.samplers.BigSampler.main(BigSampler.scala)
```

**Comment by idreeskhan** [comment]
#72 fix will likely be moving to `sbt pack` based solution, which should solve this problem as well.

**Comment by idreeskhan** [comment]
Moving to `sbt pack`, currently there is `0.3.2-SNAPSHOT` available for this and will be releasing in this manner in the future
